autoload -Uz promptinit
promptinit
#Here begins my own configs, above was autogenerated. 
setopt menu_complete
source /usr/share/autojump/autojump.sh
prompt fire
alias zshrc='$EDITOR ~/.zshrc' # Quick access to the ~/.zshrc file
alias ls='ls --color=always'
bindkey -v
export KEYTIMEOUT=1


precmd() {
  RPROMPT=""
}
zle-keymap-select() {
  RPROMPT=""
  [[ $KEYMAP = vicmd ]] && RPROMPT="%K{yellow}%B%F{yellow}[% normal]% %b%f%k"
  () { return $__prompt_status }
  zle reset-prompt
}
zle-line-init() {
  typeset -g __prompt_status="$?"
}
zle -N zle-keymap-select
zle -N zle-line-init

#/myown configs
# Set up the prompt
# prompt adam1

setopt histignorealldups sharehistory


# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=1
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
# This is the one that was prevent me from keyboard navigating the cd menu. 
# zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

#Here begins my own configs, above was autogenerated. 
setopt menu_complete
source /usr/share/autojump/autojump.sh
prompt fire
alias zshrc='$EDITOR ~/.zshrc' # Quick access to the ~/.zshrc file
alias ls='ls --color=always'
bindkey -v
